Add pre-flight to features
Signed-off-by: Jacob Woffenden <jacob.woffenden@digital.justice.gov.uk>

diff --git a/.github/workflows/features.yml b/.github/workflows/features.yml
--- a/.github/workflows/features.yml
+++ b/.github/workflows/features.yml
@@ -38,6 +38,98 @@ jobs:
         with:
           filters: .github/path-filters/features.yml
 
+  preflight-checks:
+    needs: [detect-changes]
+    if: ${{ needs.detect-changes.outputs.features != '[]' && github.ref != 'refs/heads/main' }}
+    name: Preflight Checks
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      id-token: write
+      packages: read
+    strategy:
+      fail-fast: false
+      matrix:
+        feature: ${{ fromJson(needs.detect-changes.outputs.features) }}
+    steps:
+      - name: Checkout
+        id: checkout
+        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+
+      - name: Check Version
+        id: check_version
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          echo "${{ env.GH_TOKEN }}" | skopeo login ghcr.io --username ${{ github.actor }} --password-stdin
+
+          version=$(jq -r '.version' features/src/${{ matrix.feature }}/devcontainer-feature.json)
+          export version
+
+          if skopeo list-tags docker://ghcr.io/ministryofjustice/devcontainer-feature/${{ matrix.feature }}; then
+            feature_exists=true
+          else
+            echo "feature_exists=false" >>"${GITHUB_ENV}"
+            echo "tag_exists=false" >>"${GITHUB_ENV}"
+          fi
+
+          if [[ "${feature_exists}" == "true" ]]; then
+            checkTag=$(skopeo list-tags docker://ghcr.io/ministryofjustice/devcontainer-feature/${{ matrix.feature }} | jq -r --arg version "${version}" '.Tags | index($version)')
+            export checkTag
+
+            if [[ -z "${imageTag}" ]]; then
+              echo "tag_exists=false" >>"${GITHUB_ENV}"
+            else
+              echo "tag_exists=true" >>"${GITHUB_ENV}"
+            fi
+          fi
+
+      - name: Check CHANGELOG Updates
+        id: check_changelog_updates
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          mainSha=$(gh api --method GET /repos/"${GITHUB_REPOSITORY}"/contents/features/src/${{ matrix.feature }}/CHANGELOG.md --field ref="main" | jq -r '.sha')
+          branchSha=$(gh api --method GET /repos/"${GITHUB_REPOSITORY}"/contents/features/src/${{ matrix.feature }}/CHANGELOG.md --field ref="${GITHUB_HEAD_REF}" | jq -r '.sha')
+
+          if [[ -z "${mainSha}" ]]; then
+            SHA not found for main branch, assuming CHANGELOG.md does not exist
+          elif [[ -z "${branchSha}" ]]; then
+            SHA not found for "${GITHUB_HEAD_REF}" branch, assuming CHANGELOG.md does not exist
+            "changelog_updated=false" >>"${GITHUB_ENV}"
+          elif [[ "${mainSha}" == "${branchSha}" ]]; then
+            echo "CHANGELOG.md matches main branch, needs to be updated"
+            echo "changelog_updated=false" >>"${GITHUB_ENV}"
+          elif [[ "${mainSha}" != "${branchSha}" ]]; then
+            echo "CHANGELOG.md does not match main branch, does not need to be updated"
+            echo "changelog_updated=true" >>"${GITHUB_ENV}"
+          fi
+
+      - name: Evaluate Checks
+        id: evaluate_checks
+        run: |
+          echo "::notice::# Preflight Checks"
+
+          if [[ "${{ env.tag_exists }}" == "true" ]]; then
+            echo "::error::FAIL: Feature tag already exists"
+            export failBuild="true"
+          else
+            echo "::notice::OK: Feature tag does not exist"
+            export failBuild="false"
+          fi
+
+          if [[ "${{ env.changelog_updated }}" == "true" ]]; then
+            echo "::notice::OK: CHANGELOG.md has been updated"
+            export failBuild="false"
+          elif [[ "${{ env.changelog_updated }}" == "false" ]]; then
+            echo "::error::FAIL: CHANGELOG.md needs to be updated"
+            export failBuild="true"
+          fi
+
+          if [[ "${failBuild}" == "true" ]]; then
+            exit 1
+          fi
+
   test:
     needs: [detect-changes]
     if: ${{ needs.detect-changes.outputs.features != '[]' && github.ref != 'refs/heads/main' }}
