Add newline Add README checking ADD ONBUILD
Signed-off-by: Jacob Woffenden <jacob.woffenden@digital.justice.gov.uk>

diff --git a/.github/workflows/images.yml b/.github/workflows/images.yml
--- a/.github/workflows/images.yml
+++ b/.github/workflows/images.yml
@@ -56,7 +56,7 @@ jobs:
         id: checkout
         uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
 
-      - name: Check Version (GitHub Container Registry)
+      - name: Check Version
         id: check_version
         env:
           GH_TOKEN: ${{ github.token }}
@@ -84,6 +84,51 @@ jobs:
             fi
           fi
 
+      - name: Check CHANGELOG Updates
+        id: check_changelog_updates
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          mainSha=$(gh api --method GET /repos/"${GITHUB_REPOSITORY}"/contents/containers/${{ inputs.image }}/CHANGELOG.md --field ref="main" | jq -r '.sha')
+          branchSha=$(gh api --method GET /repos/"${GITHUB_REPOSITORY}"/contents/containers/${{ inputs.image }}/CHANGELOG.md --field ref="${GITHUB_HEAD_REF}" | jq -r '.sha')
+
+          if [[ -z "${mainSha}" ]]; then
+            SHA not found for main branch, assuming CHANGELOG.md does not exist
+          elif [[ -z "${branchSha}" ]]; then
+            SHA not found for "${GITHUB_HEAD_REF}" branch, assuming CHANGELOG.md does not exist
+            "changelog_updated=false" >>"${GITHUB_ENV}"
+          elif [[ "${mainSha}" == "${branchSha}" ]]; then
+            echo "CHANGELOG.md matches main branch, needs to be updated"
+            echo "changelog_updated=false" >>"${GITHUB_ENV}"
+          elif [[ "${mainSha}" != "${branchSha}" ]]; then
+            echo "CHANGELOG.md does not match main branch, does not need to be updated"
+            echo "changelog_updated=true" >>"${GITHUB_ENV}"
+          fi
+
+      - name: Evaluate Checks
+        id: evaluate_checks
+        run: |
+          echo "::notice::# Preflight Checks"
+
+          if [[ "${{ env.tag_exists }}" == "true" ]]; then
+            echo "::error::FAIL: Container tag already exists"
+            export failBuild="true"
+          else
+            echo "::notice::OK: Container tag does not exist"
+            export failBuild="false"
+          fi
+
+          if [[ "${{ env.changelog_updated }}" == "true" ]]; then
+            echo "::notice::OK: CHANGELOG.md has been updated"
+            export failBuild="false"
+          elif [[ "${{ env.changelog_updated }}" == "false" ]]; then
+            echo "::error::FAIL: CHANGELOG.md needs to be updated"
+            export failBuild="true"
+          fi
+
+          if [[ "${failBuild}" == "true" ]]; then
+            exit 1
+          fi
 
   build-test-scan:
     needs: [detect-changes]
